services:
  db:
    build:
      context: .
      dockerfile: Docker/DockerfileMySQLWin
    hostname: db
    ports:
      - "3306:3306"

  web:
    build:
      context: .
      dockerfile: Docker/DockerfileJavaWin
    ports:
      - "80:80"
    depends_on:
      - db
