services:
  db:
    build:
      context: .
      dockerfile: Docker/DockerfileMySQLWin
      args:
        DB_VERSION: 5.7.13
    hostname: db
    ports:
      - "3306:3306"

  web:
    build:
      context: .
      dockerfile: Docker/DockerfilePythonWin
      args:
        WEB_VERSION: 3.9.3
    ports:
      - "80:80"
    depends_on:
      - db
