services:
  db-mssql:
    build:
      context: .
      dockerfile: Dockerfile.dbmssql
    ports:
      - "1433:1433"

  web:
    hostname: web
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "80:80"
    depends_on:
      - db-mssql
      