FROM mcr.microsoft.com/dotnet/sdk:8.0-windowsservercore-ltsc2022 AS build
WORKDIR /src
COPY ASPNETWebapp/ASPNETWebapp.csproj ./ASPNETWebapp/ASPNETWebapp.csproj
RUN dotnet restore ./ASPNETWebapp/ASPNETWebapp.csproj
COPY ASPNETWebapp ./ASPNETWebapp
RUN dotnet publish ./ASPNETWebapp/ASPNETWebapp.csproj -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/framework/aspnet:4.8-windowsservercore-ltsc2022

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

RUN Set-ExecutionPolicy Bypass -Scope Process -Force; \
    [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; \
    iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

RUN choco install iis-urlrewrite -y; \
    choco install iis-arr -y

RUN choco install dotnet-windowshosting --version=8.0.0 -y
RUN C:\Windows\System32\inetsrv\appcmd.exe set config -section:system.webServer/proxy /enabled:"True" /commit:apphost

RUN Remove-Item -Recurse -Force C:\inetpub\wwwroot\*

COPY --from=build /app/publish /app/api
COPY public /app/api/wwwroot

WORKDIR /app/api

COPY web.config /inetpub/wwwroot/web.config

RUN New-Item -Path 'C:\Users\Administrator' -Name 'flag.txt' -ItemType 'File' -Value 'CTF{w3Bsh3ll_asPx_adm1n}' -Force; 


ENTRYPOINT powershell -Command \
    C:\Windows\System32\inetsrv\appcmd.exe set apppool \"DefaultAppPool\" /processModel.identityType:LocalSystem; \
    C:\Windows\System32\inetsrv\appcmd.exe set config -section:system.webServer/security/authentication/anonymousAuthentication /username:\"\" /commit:apphost; \
    Start-Service W3SVC; \
    Start-Service W3SVC; \
    & "C:\app\api\ASPNETWebapp.exe"