# Set the base image (using .NET SDK to compile the app)
ARG WEB_VERSION=8.0-windowsservercore-ltsc2022
FROM mcr.microsoft.com/dotnet/aspnet:${WEB_VERSION}  AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:${WEB_VERSION}  AS build
WORKDIR /src
COPY ["ASPNETWebapp/ASPNETWebapp.csproj", "./"]
RUN dotnet restore "ASPNETWebapp.csproj"

# Copy the code 
COPY ASPNETWebapp/. .
COPY public ./wwwroot/
WORKDIR "/src/"
# RUN dotnet clean
RUN dotnet build "ASPNETWebapp.csproj" -c Release -o /app/build

# Publish the application
FROM build AS publish
RUN dotnet publish "ASPNETWebapp.csproj" -c Release -o /app/publish

# Final app image (using .NET runtime)
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "ASPNETWebapp.dll"]
