FROM node:18

WORKDIR /app

COPY package.json .
COPY app.js .
COPY mysql.js .
COPY public ./public

RUN npm install

RUN mkdir -p /root && \
    echo "FLAG{lab_ssti_test_2026}" > /root/flag.txt && \
    chmod 600 /root/flag.txt

CMD ["node", "app.js"]